"""Create alembic versions directory

Revision ID: 0001_full_schema
Revises: 
Create Date: 2026-02-13 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_full_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('sort', sa.Integer(), nullable=False, server_default='100'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('menu_period', sa.Enum('morning', 'evening', 'both', name='menuperiod'), nullable=False, server_default='both'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_menu_period'), 'categories', ['menu_period'], unique=False)
    
    op.create_table('products',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('price_rub', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('photo_url', sa.String(length=500), nullable=True),
        sa.Column('menu_period_override', sa.Enum('morning', 'evening', 'both', name='menuperiod'), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    
    # Medium Priority Fix: Delivery slot capacity management
    op.create_table('delivery_slots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slot_time', sa.String(length=20), nullable=False),
        sa.Column('max_orders', sa.Integer(), nullable=False, server_default='10'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slot_time')
    )
    
    op.create_table('orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('customer_name', sa.String(length=120), nullable=False),
        sa.Column('phone_e164', sa.String(length=32), nullable=False),
        sa.Column('address', sa.String(length=300), nullable=False),
        sa.Column('comment', sa.String(length=500), nullable=True),
        sa.Column('idempotency_key', sa.String(length=64), nullable=False),
        sa.Column('total_rub', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('new', 'accepted', 'cooking', 'on_the_way', 'delivered', 'cancelled', name='orderstatus'), nullable=False, server_default='new'),
        sa.Column('payment_method', sa.Enum('cash', 'sbp_transfer', name='paymentmethod'), nullable=False, server_default='cash'),
        sa.Column('payment_confirmed', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('delivery_mode', sa.Enum('asap', 'slot', name='deliverymode'), nullable=False, server_default='asap'),
        sa.Column('delivery_slot', sa.String(length=20), nullable=True),
        sa.Column('delivery_date', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_orders_delivery_slot'), 'orders', ['delivery_slot'], unique=False)
    op.create_index(op.f('ix_orders_phone_e164'), 'orders', ['phone_e164'], unique=False)
    
    op.create_table('order_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('name_snapshot', sa.String(length=200), nullable=False),
        sa.Column('price_rub_snapshot', sa.Integer(), nullable=False),
        sa.Column('qty', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Medium Priority Fix: Admin audit log
    op.create_table('admin_audit_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('admin_user', sa.String(length=120), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('old_values', sa.Text(), nullable=True),
        sa.Column('new_values', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    
    # Insert default delivery slots
    op.bulk_insert('delivery_slots',
        [
            {'slot_time': '10:00-12:00', 'max_orders': 15},
            {'slot_time': '12:00-14:00', 'max_orders': 20},
            {'slot_time': '14:00-16:00', 'max_orders': 20},
            {'slot_time': '16:00-18:00', 'max_orders': 15},
            {'slot_time': '18:00-20:00', 'max_orders': 10},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_delivery_slot'), table_name='orders')
    op.drop_index(op.f('ix_orders_phone_e164'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('delivery_slots')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_categories_menu_period'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
