"""add_category_parent_id

Revision ID: 0002_add_category_parent_id
Revises: 0001_full_schema
Create Date: 2026-02-14 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_add_category_parent_id'
down_revision: Union[str, None] = '0001_full_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add parent_id column to categories table
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    
    # Create index on parent_id for fast lookups
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    
    # Add foreign key constraint
    op.create_foreign_key(
        'fk_categories_parent_id', 
        'categories', 
        'categories', 
        ['parent_id'], 
        ['id'],
        ondelete='SET NULL'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraint
    op.drop_constraint('fk_categories_parent_id', 'categories', type_='foreignkey')
    
    # Drop index
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    
    # Drop column
    op.drop_column('categories', 'parent_id')
    
    # ### end Alembic commands ###
